### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by MostHated** [BrunoSilvaFreire/ShiroiFX#1]
Hey there,
    This sounds awesome, but I am a bit confused on usage. I see it comes with Unity DLL's, is the project supposed to be opened and used outside of the Unity editor? I saw that there was actual editor scripts in there as well, so I was not 100% on how I was supposed to go about utilizing this. I didn't see a demo scene in there or anything either.  I tried to look at the wiki but unfortunately, there was not much there either, and the link in the readme goes to a non-existent place. 

I am definitely interested to try this out, so if anyone has a few moments and could give me a quick rundown on setup I would greatly appreciate it.

Thanks!
-MH

**Comment by BrunoSilvaFreire** [comment]
Hey there!  

Yes, indeed the wiki pages are missing, my bad haha, I've actually been documenting a lot of stuff I've made over the last week, so expect more docs coming soon  

Answering your question: Yes and no, you see, most Unity plugins are created within the Unity Editor as if they were just another Unity project, however ShiroiFX does things a bit differently, it doesn't use the Unity Editor to generate the project files _(.sln & .csproj)_, instead we have a manual project setup, which allows us to do many cool things like:

* Use the newest features of C# while being backwards compatible with older Unity versions (which requires assemblies to be .NET 3.5 compliant)
* Have custom solution directories for assets
* Specifying details about how we want the final assembly to be built
* Having ShiroiFX being able to be used with only 4 files in the end.

The Unity assemblies are there so that anyone can safely compile the project without relying on their local Unity installation, which also makes it less bug prone, since they're using the same dll that is being used for development.  

The way you'd normally use the library is:
1. Download the latest release [here](https://github.com/LunariStudios/ShiroiFX/releases). _(Which also doesn't exist, again, my bad)_
2. Place the unzipped files in your favourite folder in unity _(I usually recommend placing it at /Assets/Plugins/ShiroiFX though)_  

However, I have not yet released the first version yet, which means your options for the while are either compiling from sources _(which if you know what you're doing, is really easy and preferred, just clone the repo and build it with MSBuild)_, or follow these steps:
1. Install [TsukiSuite](https://github.com/LunariStudios/TsukiSuite/) first _(Which I **HAVE** actually released :D)_
2. Paste the sources of [ShiroiFX](https://github.com/LunariStudios/ShiroiFX/tree/master/ShiroiFX) and [ShiroiFX-Editor](https://github.com/LunariStudios/ShiroiFX/tree/master/ShiroiFX-Editor) into your Unity Project.  

I am currently in the process of documenting and preparing my Unity libraries to be "one button click install-ish", so if things are kinda crude right now, it's because it's being worked on.  

Thanks for showing interest in the project and feel free to ask any other questions!

**Comment by MostHated** [comment]
Sounds like a solid plan, I definitely like the thought that went into the backward compatibility aspect. I very much appreciate the info. I don't personally need a 1-click solution, what you just gave should be perfect to get started. 

I will be sure to post any feedback I have for you as well,
Thanks!
-MH
